name: Developer Tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: maven:3.8.8-openjdk-8

    steps:
      - uses: actions/checkout@v3
      
      - name: Run Maven tests
        run: mvn test
